### ISSUE TITLE
Add documentation how to combine with `filterState`

### ISSUE THREAD

**Issue by alexbepple** [mathieudutour/redux-storage-decorator-migrate#10]
I started out with this:

```
const engine = migrate(
  debounceSaves(
    filterState(createEngine('my-save-key'), […]),
    saveDelay
  ),
  currentStateVersion
)
```

I was initially bugged out that `migrate` seemed to always apply all migrations. It took me a bit to suspect that my `filterState` application was filtering out the version key. I confirmed that looking at the source code of decorator-migrate.

It would be helpful to add instructions that either 
1. `filterState` should be applied after `migrate` – or
2. `filterState` should include the version key.

I went for the second option in order to make it more explicit what is going on:

```
const stateVersionProp = '_stateVersion'

const engine = migrate(
  debounceSaves(
    filterState(createEngine('my-save-key'), […, stateVersionProp]),
    saveDelay
  ),
  currentStateVersion,
  stateVersionProp
)
```

**Comment by mathieudutour** [comment]
Good point. Do you want to push a PR with a warning on the readme?

**Comment by axe312ger** [comment]
Thanks, that worked well. I just opened a pull request. Fixing spacing issues let github freak out, but looks fine now 😸
